import type { Category, CourseWithCategory } from '../types/course'

export const mockCategories: Category[] = [
  { id: '1', slug: 'web-gelistirme', name: 'Web Geliştirme', description: 'HTML, CSS, JavaScript ve modern framework\'ler', created_at: '2024-01-01' },
  { id: '2', slug: 'mobil', name: 'Mobil Geliştirme', description: 'iOS ve Android uygulama geliştirme', created_at: '2024-01-01' },
  { id: '3', slug: 'tasarim', name: 'Tasarım', description: 'UI/UX tasarım prensipleri ve araçları', created_at: '2024-01-01' },
  { id: '4', slug: 'veri-bilimi', name: 'Veri Bilimi', description: 'Python, makine öğrenmesi ve veri analizi', created_at: '2024-01-01' },
]

export const mockCourses: CourseWithCategory[] = [
  {
    id: '1',
    slug: 'react-ile-modern-web',
    title: 'React ile Modern Web Geliştirme',
    description: 'React 19, TypeScript ve Tailwind CSS kullanarak profesyonel web uygulamaları geliştirin. Hook\'lar, context, performans optimizasyonu ve daha fazlası.',
    thumbnail_url: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=640&h=360&fit=crop&auto=format',
    price: 499,
    currency: 'TRY',
    category_id: '1',
    is_published: true,
    created_at: '2024-01-10',
    updated_at: '2024-01-10',
    category: { id: '1', slug: 'web-gelistirme', name: 'Web Geliştirme' },
  },
  {
    id: '2',
    slug: 'typescript-temelden-ileri',
    title: 'TypeScript: Temelden İleriye',
    description: 'Tip güvenli kod yazmanın gücünü keşfedin. Generics, utility types, decorators ve gerçek proje deneyimi.',
    thumbnail_url: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=640&h=360&fit=crop&auto=format',
    price: 399,
    currency: 'TRY',
    category_id: '1',
    is_published: true,
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
    category: { id: '1', slug: 'web-gelistirme', name: 'Web Geliştirme' },
  },
  {
    id: '3',
    slug: 'python-veri-bilimi',
    title: 'Python ile Veri Bilimi',
    description: 'Pandas, NumPy, Matplotlib ve Scikit-learn ile veri analizi ve makine öğrenmesi modellerini öğrenin.',
    thumbnail_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=640&h=360&fit=crop&auto=format',
    price: 549,
    currency: 'TRY',
    category_id: '4',
    is_published: true,
    created_at: '2024-02-01',
    updated_at: '2024-02-01',
    category: { id: '4', slug: 'veri-bilimi', name: 'Veri Bilimi' },
  },
  {
    id: '4',
    slug: 'figma-ile-ux-tasarim',
    title: 'Figma ile UX/UI Tasarım',
    description: 'Kullanıcı odaklı tasarım süreçlerini, prototipleme tekniklerini ve Figma\'nın tüm özelliklerini öğrenin.',
    thumbnail_url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=640&h=360&fit=crop&auto=format',
    price: 349,
    currency: 'TRY',
    category_id: '3',
    is_published: true,
    created_at: '2024-02-10',
    updated_at: '2024-02-10',
    category: { id: '3', slug: 'tasarim', name: 'Tasarım' },
  },
  {
    id: '5',
    slug: 'react-native-mobil',
    title: 'React Native ile Mobil Uygulama',
    description: 'Tek kod tabanıyla iOS ve Android uygulamaları geliştirin. Navigation, native API\'lar ve yayınlama süreci.',
    thumbnail_url: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=640&h=360&fit=crop&auto=format',
    price: 449,
    currency: 'TRY',
    category_id: '2',
    is_published: true,
    created_at: '2024-03-01',
    updated_at: '2024-03-01',
    category: { id: '2', slug: 'mobil', name: 'Mobil Geliştirme' },
  },
  {
    id: '6',
    slug: 'nodejs-backend',
    title: 'Node.js ile Backend Geliştirme',
    description: 'Express, REST API, authentication, veritabanı entegrasyonu ve deployment. Gerçek dünya projeleriyle öğrenin.',
    thumbnail_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=640&h=360&fit=crop&auto=format',
    price: 479,
    currency: 'TRY',
    category_id: '1',
    is_published: true,
    created_at: '2024-03-15',
    updated_at: '2024-03-15',
    category: { id: '1', slug: 'web-gelistirme', name: 'Web Geliştirme' },
  },
]
